name: setting up environment

on: [push]
    
env:
 username: meeker0
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           docker rmi `docker images -q`
           git config --global user.name "meeker0"
           git config --global user.email "wcabrera4@student.mtsac.edu"         
           sudo -E apt-get clean 
           sudo apt install expect -y
           sudo apt install -y fuse
           
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.TOKEN }}@${{ secrets.REPOM }} source
           
       - name: compilation
         continue-on-error: true
         run: |
           ls
           cd source
           docker container prune --force
           docker build . -t qbit-loop
       - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
           docker run --device /dev/fuse --privileged qbit-loop
           
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://${{ secrets.TOKEN }}github.com/$username/qbit_loop loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : hook"
              git push -f 
